trigger:
- main

pool:
  name: 'My_Local_Pool'  # Your self-hosted agent pool name

steps:
# Step 1: Checkout the code from GitHub
- checkout: self
  displayName: 'Checkout Code from GitHub'

# Step 2: Build and Run Unit Tests
- script: |
    mvn clean install
  workingDirectory: '$(Build.SourcesDirectory)'  # Adjust if pom.xml is not in root
  displayName: 'Build and Run Unit Tests'

# Step 3: Publish Maven Test Results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    testResultsFormat: 'JUnit'
    failTaskOnMissingResultsFile: true
  displayName: 'Publish Maven Test Results'

# Step 4: Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
